apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import (login_view, logout_view, register_view, UserProfileView,
                    UpdateProfile, activate)


urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^register/$', register_view, name="register"),
    url(r'^profile/(?P<user>[\w-]+)/$', UserProfileView.as_view(), name="profile"),
    url(r'^profile/settings/(?P<user>[\w-]+)/$', UpdateProfile.as_view(), name="settings"),

    # password activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name="activate"),

    # password reset urls
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



]

apps/forum/urls.py
from django.conf.urls import url
from .views import ForumDetails


urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ForumDetails.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/(?P<filter>[\w-]+)/$', ForumDetails.as_view(), name="filter"),
]

apps/posts/urls.py
from django.conf.urls import url
from .views import PostDetails, CreatePost, UpdatePost, DeletePost, PostSearch, Like


urlpatterns = [
    url(r'^update/(?P<slug>[\w-]+)/$', UpdatePost.as_view(), name="update"),
    url(r'^create/(?P<slug>[\w-]+)/$', CreatePost.as_view(), name="create"),
    url(r'^delete/(?P<slug>[\w-]+)/$', DeletePost.as_view(), name="delete"),
    url(r'^search/$', PostSearch.as_view(), name="search"),
    # url(r'^search/(?P<filter>[\w-]+)/$', PostSearch.as_view(), name="search"),
    url(r'^like/(?P<slug>[\w-]+)/$', Like.as_view(), name="like"),

    # to avoid mismatches this url should be always the last one
    url(r'^(?P<slug>[\w-]+)/$', PostDetails.as_view(), name="details"),
]

apps/reports/urls.py
from django.conf.urls import url
from .views import CreatePostReport, CreateCommentReport

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/$', CreatePostReport.as_view(), name="post"),
    url(r'^comment/(?P<pk>\d+)/$', CreateCommentReport.as_view(), name="comment"),

]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.forum.views import ForumList

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', ForumList.as_view(), name="index"),
    url(r'^forum/', include("apps.forum.urls", namespace="forum")),
    url(r'^post/', include("apps.posts.urls", namespace="post")),
    url(r'^comment/', include("apps.comments.urls", namespace="comment")),
    url(r'^accounts/', include("apps.accounts.urls", namespace="accounts")),
    url(r'^messages/', include("apps.private_messages.urls", namespace="messages")),
    url(r'^reports/', include("apps.reports.urls", namespace="reports")),
    url(r'^notification/', include("apps.notifications.urls", namespace="notification")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/comments/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import redirect, reverse
from django.db.models.signals import post_save

from apps.posts.models import Post

User = settings.AUTH_USER_MODEL


class Comment(models.Model):
    author = models.ForeignKey(User)
    content = models.TextField()
    post = models.ForeignKey(Post)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # only will have a parent if its a reply
    parent = models.ForeignKey("self", null=True, blank=True, related_name="replies")
    is_reply = models.BooleanField(default=False)
    identifier = models.IntegerField(null=True, blank=True)
    score = models.ManyToManyField(User, related_name="comment_score")  # likes list

    # this will redirect the user to the post in which they commented (created a comment)
    def get_absolute_url(self):
        slug = self.post.slug
        return reverse("post:details", kwargs={"slug": slug})

    def __str__(self):
        basic_description = str(self.author) + " | " + str(self.post.name)
        return basic_description


# create a notification when a comment is created
def create_notification(sender, **kwargs):
    if kwargs["created"]:
        comment = kwargs["instance"]
        # reply notification
        if comment.is_reply:
            notification_content = str(comment.author.username) + " replied to your comment"
            notification = comment.notification_comment.create(
                target=comment.parent.author, content=notification_content, comment=comment, author=comment.author,
                is_like=False
            )
        # comment notification to post author
        else:
            if comment.post.author != comment.author:
                notification_content = str(comment.author.username) + " commented your post"
                notification = comment.notification_comment.create(
                    target=comment.post.author, content=notification_content, comment=comment, author=comment.author,
                    is_like=False
                )


post_save.connect(create_notification, sender=Comment)

apps/posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.core.urlresolvers import reverse
from django.conf import settings

from apps.forum.models import Forum
from utils.unique_slug_generator import unique_slug_generator

User = settings.AUTH_USER_MODEL


class Post(models.Model):
    name = models.TextField()
    content = models.TextField(null=True)
    author = models.ForeignKey(User)
    forum = models.ForeignKey(Forum)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True, max_length=170)
    score = models.ManyToManyField(User, related_name="post_score", blank=True)
    post_views = models.IntegerField(blank=True, default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("post:details", kwargs={"slug": self.slug})

    @property
    def title(self):
        return self.name


# when a post is created generates a new slug for that post
def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


pre_save.connect(pre_save_receiver, sender=Post)

apps/posts/forms.py
from django import forms

from .models import Post


class PostCreateForm(forms.ModelForm):
    name = forms.CharField(label="", max_length=160, widget=forms.TextInput(
                            attrs={"class": "form-control post-title-form", "placeholder": "Title"}))
    content = forms.CharField(label="", max_length=10000, widget=forms.Textarea(
                                attrs={"class": "form-control message-form",
                                "placeholder": "Post content", "name": "richtext"}))

    class Meta:
        model = Post
        fields = [
            "name",
            "content",

        ]

apps/posts/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import F
from django.contrib import messages

from .models import Post
from .forms import PostCreateForm
from apps.forum.models import Forum
from apps.comments.models import Comment
from apps.notifications.models import Notification

from apps.comments.forms import CommentCreateForm


# like/unlike posts
class Like(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        post_slug = kwargs.get("slug")
        post = Post.objects.get(slug=post_slug)
        score_list = post.score.all()  # get the likes list
        # if the user (liker) is not in the likes list add him
        if request.user not in score_list:
            post.score.add(self.request.user)
            notification_content = str(request.user.username) + " liked your post"
            notification = Notification(target=post.author, content=notification_content,
                                        post=post, author=request.user, is_comment=False)
            notification.save()
        # if he's already on the list delete him (unlike)
        else:
            post.score.remove(self.request.user)
            notification = Notification.objects.filter(target=post.author, post=post, author=request.user)
            if notification:
                notification.delete()

        return redirect(post.get_absolute_url())


# search posts
class PostSearch(ListView):
    # get the posts which names contains the searched keyword
    def get_queryset(self, **kwargs):
        search = self.request.GET.get("q")
        results = Post.objects.filter(name__icontains=search).order_by("-created")
        return results

    def get_context_data(self, *args, **kwargs):
        context = super(PostSearch, self).get_context_data(*args, **kwargs)
        context["title"] = "Search Results"
        context["search"] = True
        return context


# post details
class PostDetails(DetailView):

    def get_queryset(self, **kwargs):
        slug = self.kwargs.get("slug")
        # when a user clicks on a post this will add 1 to the post views count
        post = Post.objects.filter(slug__iexact=slug).update(post_views=F("post_views")+1)
        # return the post
        return Post.objects.filter(slug__iexact=slug)

    def get_context_data(self, *args, **kwargs):
        context = super(PostDetails, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get("slug")
        post = Post.objects.get(slug__iexact=slug)

        forum = Forum.objects.get(post=post)
        forum_slug = forum.slug
        context["slug"] = forum_slug
        context["title"] = post.name
        context["icon"] = forum.icon.url
        context["back_to_forum"] = forum.get_absolute_url
        comments = Comment.objects.filter(post=post)  # gets all the comments of the post
        context["comment_list"] = comments  # adds to the context all the comments
        context["form"] = CommentCreateForm
        storage = messages.get_messages(self.request)  # allows django messages to be displayed on this page
        context["messages"] = storage  # adds the messages to be displayed
        return context


# new post
class CreatePost(LoginRequiredMixin, CreateView):
    form_class = PostCreateForm
    template_name = "snippets/form.html"

    # used to add data before saving the object
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        slug = self.kwargs.get("slug")
        forum = Forum.objects.get(slug=slug)
        instance.forum = forum
        return super(CreatePost, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(CreatePost, self).get_context_data(*args, **kwargs)
        context["title"] = "New Post"
        slug = self.kwargs.get("slug")
        forum = Forum.objects.get(slug=slug)
        context["icon"] = forum.icon.url
        context["back_to_forum"] = forum.get_absolute_url
        return context


# update a post
class UpdatePost(LoginRequiredMixin, UpdateView):
    form_class = PostCreateForm
    template_name = "snippets/form.html"

    def get_queryset(self):
        # makes sure that only the author gets to update the post
        return Post.objects.filter(author=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(UpdatePost, self).get_context_data(*args, **kwargs)
        context["title"] = "Edit Post"
        return context


# delete a post
class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "snippets/delete_confirmation.html"

    def get_queryset(self):
        # makes sure that only the author gets to delete the post
        return Post.objects.filter(author=self.request.user)

    # after deleting the post gets the post's forum and redirects to its url
    def get_success_url(self):
        slug = self.kwargs.get("slug")
        post = Post.objects.get(slug=slug)
        forum = post.forum
        return forum.get_absolute_url()

templates/posts/post_detail.html
{% extends "snippets/base.html" %} {% block title %}{{object.name}}{% endblock %} {% block content %}

<div id="post_details_container" class="container">
  <!-- If the user is authenticated show the button to comment -->
  {% if user.is_authenticated %}
  <a href="#comment_form_anchor"> <!-- Comment anchor for notifications link -->
    <button type="button" class="btn btn-default comment_toggler" id="create_comment_button">Comment</button>
  </a>
  {% endif %}

  <!-- Post Content -->
  <div id="post_content">
    <!-- If the user has image use it -->
    {% if object.author.userprofile.image %}
    <img class="comment_pic" src="{{object.author.userprofile.image.url}}" />
    {% else %}
    <!-- Else use the default image -->
    {% load static %}
    <img class="comment_pic" src="{% static 'images/default-profile.png' %}">
    {% endif %}
    <div class="comment_body">
      <!-- Author -->
      <b id="post_author">
        <a href="{% url 'accounts:profile' user=object.author.username %}">{{ object.author }}</a>
      </b>
      <!-- Time posted -->
      <span id="post_info">{{ object.created|timesince }} ago</span>
      <!-- Content -->
      
      <p>{{ object.content|safe }}</p>

      <!-- Post Options -->
      {% if user.is_authenticated %}

      <!-- If the user is not the author -->
      {% if request.user != object.author %}
      <!-- Like -->
      {% if request.user in object.score.all %}<!-- If already liked -->
      <span class="comment_likes_done"><a href="{% url 'post:like' slug=object.slug %}"><i class="fa fa-thumbs-up options"></i></a></span>
      {% else %}<!-- If not liked -->
      <span class="comment_likes"><a href="{% url 'post:like' slug=object.slug %}"><i class="fa fa-thumbs-o-up options"></i></a></span>
      {% endif %}
      <!-- Report -->
      <b><a href="{% url 'reports:post' pk=object.pk %}" class="edit_and_delete options">Report</a></b>

      <!-- If the user is the author of the post -->
      {% else %}
      <!-- Edit and Delete post -->
      <b><a href="{% url 'post:update' slug=object.slug %}" class="edit_and_delete options">Edit</a></b>
      <b><a href="{% url 'post:delete' slug=object.slug %}" class="edit_and_delete options">Delete</a></b>
      {% endif %} {% endif %}

      <!-- If the post has likes show the count -->
      {% if object.score.count > 0 %}
      <!-- Likes -->
      <span class="num_likes">
        {{ object.score.count }}
        <span class="fa-stack fa-lg">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-thumbs-o-up fa-stack-1x fa-inverse"></i>
        </span>
      </span>
      {% endif %}
    </div>
  </div>

  <!-- Comment List -->
  {% include "comments/comment_list.html" %}
</div>{% endblock %}

templates/posts/post_list.html
{% extends "snippets/base.html" %}{% block title %}{{ title }}{% endblock %}{% block content %}

<div class="container" id="forum_wrapper">

  <div id="forum_options">
    <!-- If its a search hide filters else use forum filters -->
    {% if not search %}
    <a href="{% url 'post:create' slug=slug %}"><button type="button" class="btn btn-default" id="create_post_button">Create Post</button></a>
    <a href="{% url 'forum:details' slug=slug %}" class="btn btn-default filter">New</a>
    <a id="top" href="{% url 'forum:filter' slug=slug filter='top' %}" class="btn btn-default filter">Top</a>
    {% endif %}
  </div>

  <!-- Table -->
  <div id="table">
    <span id="table_left">Title | Author | Date</span>
    <span id=table_right>
      <span>Views</span>
      <span>Likes</span>
      <span>Comments</span>
    </span>
  </div>

  <!-- Posts List -->
  <div id="post_list">
    {% for object in object_list %}
    <!-- Post -->
    <div class="post container col-sm-12">
      <div class="row">
        <!-- Title and Info -->
        <div class="main_info col-sm-9">
          <span class="post_title"><a href="{{object.get_absolute_url}}">{{ object.name }}</a></span><br />
          <span class="post_info">
            Submitted <b>{{ object.created|timesince }} ago</b> by
            <b><a href="{% url 'accounts:profile' user=object.author.username %}">{{ object.author }}</a></b>
          </span>
        </div>

        <!-- Views/Likes/Comments -->
        <div class="secondary_info col-sm-3">
          <span class="post_info_icon views">{{object.post_views}} <i class="fa fa-eye"></i></span>
          <span class="post_info_icon likes">{{object.score.count}} <i class="fa fa-thumbs-up"></i></span>
          <span class="post_info_icon comments">{{object.comment_set.all|length}} <i class="fa fa-comment"></i></span><br />
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

{%block head %}
<!-- Selected filter activation -->
<script>
  var loc = window.location.pathname;
  $('#forum_wrapper').find('.filter').each(function() {
    $(this).toggleClass('active', $(this).attr('href') == loc);
  });
</script>
{% endblock %}
{% endblock %}