apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import (login_view, logout_view, register_view, UserProfileView,
                    UpdateProfile, activate)


urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^register/$', register_view, name="register"),
    url(r'^profile/(?P<user>[\w-]+)/$', UserProfileView.as_view(), name="profile"),
    url(r'^profile/settings/(?P<user>[\w-]+)/$', UpdateProfile.as_view(), name="settings"),

    # password activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name="activate"),

    # password reset urls
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



]

apps/posts/urls.py
from django.conf.urls import url
from .views import PostDetails, CreatePost, UpdatePost, DeletePost, PostSearch, Like


urlpatterns = [
    url(r'^update/(?P<slug>[\w-]+)/$', UpdatePost.as_view(), name="update"),
    url(r'^create/(?P<slug>[\w-]+)/$', CreatePost.as_view(), name="create"),
    url(r'^delete/(?P<slug>[\w-]+)/$', DeletePost.as_view(), name="delete"),
    url(r'^search/$', PostSearch.as_view(), name="search"),
    # url(r'^search/(?P<filter>[\w-]+)/$', PostSearch.as_view(), name="search"),
    url(r'^like/(?P<slug>[\w-]+)/$', Like.as_view(), name="like"),

    # to avoid mismatches this url should be always the last one
    url(r'^(?P<slug>[\w-]+)/$', PostDetails.as_view(), name="details"),
]

apps/private_messages/urls.py
from django.conf.urls import url
from .views import PMList, CreatePM, SentList, ReplyPM, DeletePM, ProfilePM

urlpatterns = [
    url(r'^inbox/$', PMList.as_view(), name="inbox"),
    url(r'^sent/$', SentList.as_view(), name="sent"),
    url(r'^create/$', CreatePM.as_view(), name="create"),
    url(r'^reply/(?P<contact>[\w-]+)/(?P<pk>\d+)/$', ReplyPM.as_view(), name="reply"),
    url(r'^delete/(?P<pk>\d+)/$', DeletePM.as_view(), name="delete"),
    url(r'^create/(?P<contact>[\w-]+)/$', ProfilePM.as_view(), name="profile_message"),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.forum.views import ForumList

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', ForumList.as_view(), name="index"),
    url(r'^forum/', include("apps.forum.urls", namespace="forum")),
    url(r'^post/', include("apps.posts.urls", namespace="post")),
    url(r'^comment/', include("apps.comments.urls", namespace="comment")),
    url(r'^accounts/', include("apps.accounts.urls", namespace="accounts")),
    url(r'^messages/', include("apps.private_messages.urls", namespace="messages")),
    url(r'^reports/', include("apps.reports.urls", namespace="reports")),
    url(r'^notification/', include("apps.notifications.urls", namespace="notification")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save

User = settings.AUTH_USER_MODEL


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    image = models.ImageField(upload_to="profile/", blank=True, null=True)

    def __str__(self):
        return self.user.username

    # When a user is created, create his profile
    def create_profile(sender, **kwargs):
        if kwargs["created"]:
            user_profile = UserProfile.objects.create(user=kwargs["instance"])

    post_save.connect(create_profile, sender=User)

apps/comments/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import redirect, reverse
from django.db.models.signals import post_save

from apps.posts.models import Post

User = settings.AUTH_USER_MODEL


class Comment(models.Model):
    author = models.ForeignKey(User)
    content = models.TextField()
    post = models.ForeignKey(Post)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # only will have a parent if its a reply
    parent = models.ForeignKey("self", null=True, blank=True, related_name="replies")
    is_reply = models.BooleanField(default=False)
    identifier = models.IntegerField(null=True, blank=True)
    score = models.ManyToManyField(User, related_name="comment_score")  # likes list

    # this will redirect the user to the post in which they commented (created a comment)
    def get_absolute_url(self):
        slug = self.post.slug
        return reverse("post:details", kwargs={"slug": slug})

    def __str__(self):
        basic_description = str(self.author) + " | " + str(self.post.name)
        return basic_description


# create a notification when a comment is created
def create_notification(sender, **kwargs):
    if kwargs["created"]:
        comment = kwargs["instance"]
        # reply notification
        if comment.is_reply:
            notification_content = str(comment.author.username) + " replied to your comment"
            notification = comment.notification_comment.create(
                target=comment.parent.author, content=notification_content, comment=comment, author=comment.author,
                is_like=False
            )
        # comment notification to post author
        else:
            if comment.post.author != comment.author:
                notification_content = str(comment.author.username) + " commented your post"
                notification = comment.notification_comment.create(
                    target=comment.post.author, content=notification_content, comment=comment, author=comment.author,
                    is_like=False
                )


post_save.connect(create_notification, sender=Comment)

apps/accounts/forms.py
from django import forms
from django.contrib.auth import authenticate, get_user_model

User = get_user_model()


# Change image form
class ProfileImageForm(forms.ModelForm):
    image = forms.ImageField(label="")

    class Meta:
        model = User
        fields = [
            "image",
        ]


# login form
class UserLoginForm(forms.Form):
    username = forms.CharField(label="", max_length=25, widget=forms.TextInput(attrs={"placeholder": "Username"}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={"placeholder": "Password"}))

    # if the user/password combination does not exists raise an error
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)  # not login, only checking if it exists
        if not user:
            raise forms.ValidationError("Incorrect username or password.")

        return super(UserLoginForm, self).clean(*args, **kwargs)


# register form
class UserRegisterForm(forms.ModelForm):
    username = forms.CharField(label="", max_length=25, widget=forms.TextInput(attrs={"placeholder": "Username"}))
    password = forms.CharField(label="", widget=forms.PasswordInput(attrs={"placeholder": "Password"}))
    password2 = forms.CharField(label="", widget=forms.PasswordInput(attrs={"placeholder": "Password Confirmation"}))
    email = forms.EmailField(label="", widget=forms.TextInput(attrs={"placeholder": "Email"}))

    class Meta:
        model = User
        fields = [
            "username",
            "password",
            "password2"
        ]

    def clean(self, *args, **kwargs):
        password = self.cleaned_data.get("password")  # password
        password2 = self.cleaned_data.get("password2")  # password confirmation
        # if the password and the password confirmation are not the same raise an error
        if password != password2:
            raise forms.ValidationError("Passwords must match")

        # if there is a user with that username raise an error
        username = self.cleaned_data.get("username")
        username_qs = User.objects.filter(username=username)
        if username_qs.exists():
            raise forms.ValidationError("This username has already been registered")

        email = self.cleaned_data.get("email")
        email_qs = User.objects.filter(email=email)
        # if the email is already registered raise an error
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered")

        return super(UserRegisterForm, self).clean(*args, **kwargs)

apps/accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.views.generic import ListView, View
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.core.mail import EmailMessage
from django.contrib import messages

from .forms import UserLoginForm, UserRegisterForm, ProfileImageForm
from .models import UserProfile
from apps.posts.models import Post
from apps.comments.models import Comment
from .tokens import account_activation_token

User = get_user_model()


# View used to update the user profile (password and image)
class UpdateProfile(LoginRequiredMixin, View):
    template_name = "accounts/settings.html"

    # passes the password/image forms and the title to settings.html
    def get(self, request, *args, **kwargs):
        password_update = PasswordChangeForm(user=request.user)
        image_update = ProfileImageForm
        context = {
            "password_form": password_update,
            "image_form": image_update,
            "title": "Settings",
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        # get the forms with the data
        image_form = ProfileImageForm(request.POST, request.FILES)
        password_form = PasswordChangeForm(data=request.POST, user=request.user)
        # if the password form is valid save it
        if password_form.is_valid():
            password_form.save()
            messages.success(self.request, "Your password has been updated, please log in again.")
            return redirect("index")

        # if the image form is valid set the profile image to the submitted image and save it
        if image_form.is_valid():
            profile = UserProfile.objects.get(user=request.user)
            profile.image = image_form.cleaned_data["image"]
            profile.save()
            return redirect("index")

        # if the form is not valid return it again
        context = {
            "password_form": PasswordChangeForm(user=request.user),
            "image_form": ProfileImageForm,
            "title": "Settings",
        }
        return render(request, self.template_name, context)


# view to display the user profile page
class UserProfileView(ListView):
    template_name = "accounts/user_profile.html"

    def get_queryset(self):
        return None

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)

        # add the username to context and get the user object
        username = self.kwargs.get("user")
        context["username"] = username
        user = User.objects.get(username=username)
        # set the title
        context["title"] = "Overview for " + str(username)
        # filter all the posts where the author is the user and order them by newest
        posts = Post.objects.filter(author=user).order_by("-created")
        context["posts_list"] = posts
        # filter all the comments where the author is the user and order them by newest
        comments = Comment.objects.filter(author=user).order_by("-created")
        context["comments_list"] = comments
        # if the user has a profile image pass it, else the default image will be set on the template
        if user.userprofile.image:
            context["profile_picture"] = user.userprofile.image.url
        return context


# function to login users
def login_view(request):
    # GET part
    form = UserLoginForm(request.POST or None)  # get the form with the data (if posted) or empty (if get)
    is_login = True  # when its true the template will be styled for the login, else for the registration
    context = {
        "form": form,
        "title": "Login",
        "login": is_login,
    }
    template_name = "accounts/form.html"

    # POST part
    # if the form is valid the user will be authenticated and logged
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        next_url = request.GET.get("next")
        if next_url:
            return HttpResponseRedirect(next_url)
        else:
            return redirect("index")

    # if its a get request or the posted form is not valid render the form
    return render(request, template_name, context)


# function used to register users
def register_view(request):
    form = UserRegisterForm(request.POST or None)
    # if the form is valid set the user object and save it
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        user.set_password(password)
        user.is_active = False
        user.email = form.cleaned_data.get("email")
        user.save()

        current_site = get_current_site(request)
        # get the template + data and create the email message
        message = render_to_string("accounts/acc_activate_email.html", {
            "user": user,
            "domain": current_site.domain,
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "token": account_activation_token.make_token(user),

        })
        # set the email subject
        mail_subject = "Active your GForum account."
        # set the email address
        to_email = form.cleaned_data.get("email")
        # get the message, subject and address and send the email
        email = EmailMessage(mail_subject, message, to=[to_email])
        email.send()

        messages.info(request, "A confirmation email has been sent to your email address.")
        return redirect("index")

    template_name = "accounts/form.html"
    context = {
        "form": form,
        "title": "Sign Up"
    }

    # if its a get request or the posted form is not valid render the form
    return render(request, template_name, context)


# logout function
def logout_view(request):
    logout(request)
    return redirect("index")


# function to activate the user account
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))  # get the uid from the activation token
        user = User.objects.get(pk=uid)  # get the user with the uid
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    # if the link is valid activate the account and login the user, else return an error message
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)

        messages.success(request, "Your account has been activated! Now you can login and enjoy GForum.")
        return redirect("index")
    else:
        messages.error(request,
                       """The activation link was invalid, possibly because it has already been used.
                        Please contact us.""")
        return redirect("index")

templates/accounts/acc_activate_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link below to confirm your registration on GForum,

http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

If clicking the link above doesn't work, please copy and paste the URL in a new browser
window instead.

Sincerely,
The GForum Team
{% endautoescape %}

templates/accounts/form.html
{% extends "snippets/base.html" %}{% block title %}{{ title }}{% endblock %}{% block content %}

<div class="container" id="login_register_wrapper">
  <div id="login_register_container">

    <!-- Login/Register Form -->
    <form method="post" class="main_form">
      {% csrf_token %}
      {{ form.as_p }}
      <input id="login_register_button" class="btn btn-default" type="submit" value="{{title}}" />
      <input type="hidden" name="next" value="{{ next }}" />
    </form>

    <!-- Second option -->
    <div id="login_register_misc">
      {% if login %} <!-- If login show option to register -->
      <span class="reverse_option">Don't have an account?
        <b><a href="{% url 'accounts:register' %}">Sign up</a></b>
      </span>
      <br/>
      <a href="{% url 'accounts:password_reset' %}" class="forgot_pass"><span>Forgot your password?</span></a>
      {% else %}<!-- If register show option to login -->
      <span class="reverse_option">Already have an account?
        <b><a href="{% url 'accounts:login' %}">Login</a></b>
      </span>
      {% endif %}
    </div>

  </div>
  <!-- Terms and Conditions -->
  {% if not login %}
  <span id="terms_policy">
    By signing up, you agree to our <a href="#">Terms</a> and that you have read our <a href="#">Privacy Policy</a>
     and <a href="#">Content Policy</a>.
  </span>
  {% endif %}
</div>
{% endblock %}

templates/accounts/settings.html
{% extends "snippets/base.html" %}{% block title %}{{ title }}{% endblock %}{% block content %}

<div class="container" id="settings_container">
  <!-- Update Image -->
  <div id="image_form">
    <h4>Update Image</h4>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ image_form.as_p }}
      <input type="submit" value="Update" class="btn btn-default update_button"/>
    </form>
  </div>

  <!-- Update Password -->
  <div id="password_form">
    <h4>Update Password</h4>
    <form method="post" action="">
      {% csrf_token %}
      {{ password_form.as_p }}
      <input type="submit" value="Update" class="btn btn-default update_button"/>
    </form>
  </div>

</div>{% endblock %}

templates/accounts/user_profile.html
{% extends "snippets/base.html" %}{% block title %}{{ title }}{% endblock %}{% block content %}

<div class="container" id="profile_container">

  <!-- If is another user profile show the button to contact -->
  {% if username != request.user.username %}
  <a href="{% url 'messages:profile_message' contact=username %}"><button type="button" class="btn btn-default contact_user_button">
    <i class="fa fa-envelope-o"></i></button></a>
  {% endif %}

  <div class="container user_profile_wrapper">
    <div class="row">

      <!-- User posts list -->
      <div class="col-sm-6 user_profile_posts">
        <h1>Posts</h1>
        <!-- If there are no posts show a message -->
        {% if not posts_list.all%}
        <h3 class="empty_userprofile">This user has no posts</h3>
        {% endif %}

        <!-- Post -->
        {% for post in posts_list %}
        <div class="userprofile_post">
          <!-- Post Forum icon -->
          <a href="{{post.forum.get_absolute_url}}">
            <img class="profile_post_icon" src="{{post.forum.icon.url}}" />
          </a>
          <!-- Title -->
          <h4><a href="{{ post.get_absolute_url }}">{{ post.name }}</a></h4>
          <!-- Time Since -->
          <span class="post_info">Submitted <b>{{ post.created|timesince }} ago</b></span>
          <!-- Content -->
          <p>{{ post.content |safe }}</p>

          <!-- Options -->
          {% if user.is_authenticated and request.user == post.author %}
            <b><a href="{% url 'post:update' slug=post.slug %}" class="profile_edit_and_delete">Edit</a></b>
            <b><a href="{% url 'post:delete' slug=post.slug %}" class="profile_edit_and_delete">Delete</a></b>
          {% endif %}
          <!-- Number of likes and comments -->
          <span class="post_list_likes">{{post.score.count}} <i class="fa fa-thumbs-up"></i></span>
          <span class="post_list_comments">{{post.comment_set.all|length}}
            <i class="fa fa-comment"></i>
          </span><br />
        </div>
        {% endfor %}
      </div>

      <!-- User comments list -->
      <div class="col-sm-6 user_profile_comments">
        <h1>Comments</h1>
        <!-- If there are no posts show a message -->
        {% if not comments_list.all%}
        <h3 class="empty_userprofile">This user has no comments</h3>
        {% endif %}

        <!-- Comment -->
        {% for comment in comments_list %}
        <div class="comment_wrapper"> <!-- Needed to allow the parent content popup to overflow -->
          <div class="userprofile_comment commentContainer">
            <!-- Identifier -->
            <span class="comment_identifier">#{{ comment.identifier }} </span>
            <!-- Author -->
            <b class="comment_author">{{ comment.author }}</b>
            <!-- Time since -->
            <span class="comment_info"> {{ comment.created|timesince }} ago on
              <b><a href="{{comment.post.get_absolute_url}}">{{ comment.post.name }}</a></b>
            </span>

            <!--- If its a reply show parent identifier and content on hover --->
            {% if comment.is_reply %}
              <br /><div class="reply_parent">@{{ comment.parent.identifier }}</div>
              <!--- Parent content --->
              <div class="parent_content">
                <b>{{ comment.parent.author }}</b>
                <p class="parent_content_body">{{ comment.parent.content | safe }}</p>
              </div>
            {% endif %}

            <!--- Content --->
            <p>{{ comment.content | safe }}</p>
            <!--- Options --->
            {% if comment.author == request.user %}
              <b><a href="{% url 'comment:update' pk=comment.pk %}" class="profile_edit_and_delete">Edit</a></b>
              <b><a href="{% url 'comment:delete' pk=comment.pk %}" class="profile_edit_and_delete">Delete</a></b>
            {% endif %}

          </div>
        </div>
        {% endfor %}

      </div>
    </div>
  </div>
</div>

{% endblock %}