apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import (login_view, logout_view, register_view, UserProfileView,
                    UpdateProfile, activate)


urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^register/$', register_view, name="register"),
    url(r'^profile/(?P<user>[\w-]+)/$', UserProfileView.as_view(), name="profile"),
    url(r'^profile/settings/(?P<user>[\w-]+)/$', UpdateProfile.as_view(), name="settings"),

    # password activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name="activate"),

    # password reset urls
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



]

apps/forum/urls.py
from django.conf.urls import url
from .views import ForumDetails


urlpatterns = [
    url(r'^(?P<slug>[\w-]+)/$', ForumDetails.as_view(), name="details"),
    url(r'^(?P<slug>[\w-]+)/(?P<filter>[\w-]+)/$', ForumDetails.as_view(), name="filter"),
]

apps/posts/urls.py
from django.conf.urls import url
from .views import PostDetails, CreatePost, UpdatePost, DeletePost, PostSearch, Like


urlpatterns = [
    url(r'^update/(?P<slug>[\w-]+)/$', UpdatePost.as_view(), name="update"),
    url(r'^create/(?P<slug>[\w-]+)/$', CreatePost.as_view(), name="create"),
    url(r'^delete/(?P<slug>[\w-]+)/$', DeletePost.as_view(), name="delete"),
    url(r'^search/$', PostSearch.as_view(), name="search"),
    # url(r'^search/(?P<filter>[\w-]+)/$', PostSearch.as_view(), name="search"),
    url(r'^like/(?P<slug>[\w-]+)/$', Like.as_view(), name="like"),

    # to avoid mismatches this url should be always the last one
    url(r'^(?P<slug>[\w-]+)/$', PostDetails.as_view(), name="details"),
]

apps/reports/urls.py
from django.conf.urls import url
from .views import CreatePostReport, CreateCommentReport

urlpatterns = [
    url(r'^post/(?P<pk>\d+)/$', CreatePostReport.as_view(), name="post"),
    url(r'^comment/(?P<pk>\d+)/$', CreateCommentReport.as_view(), name="comment"),

]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.forum.views import ForumList

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', ForumList.as_view(), name="index"),
    url(r'^forum/', include("apps.forum.urls", namespace="forum")),
    url(r'^post/', include("apps.posts.urls", namespace="post")),
    url(r'^comment/', include("apps.comments.urls", namespace="comment")),
    url(r'^accounts/', include("apps.accounts.urls", namespace="accounts")),
    url(r'^messages/', include("apps.private_messages.urls", namespace="messages")),
    url(r'^reports/', include("apps.reports.urls", namespace="reports")),
    url(r'^notification/', include("apps.notifications.urls", namespace="notification")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}GForum{% endblock %}</title>
    {% include 'snippets/bootstrap.html' %}
    {% include 'snippets/javascript.html' %}
    {% include 'snippets/general_style.html' %}
    {% block head %} {% endblock %}
</head>
<body>

<!-- Header and Navbar -->
  <header id="header">
    {% include "snippets/nav.html" %}
    <div class="header_separator"></div>
    <div class="title">
      <div class="container">
        <!-- If there is a forum icon display it, else display profile picture
        (will display only on a users profile) -->
        {% if icon %}
        <a href="{{ back_to_forum }}"><img src="{{icon}}"/></a>
        {% else %}
        <img id="profile_picture" src="{{profile_picture}}"/>
        {% endif %}
        <span id="forum_title">{{title}}</span>
      </div>
    </div>
  </header>

  <!-- Display Django Messages -->
  {% include "snippets/display_messages.html" %}

  <!-- Main Content -->
  {% block content %}{% endblock %}
</body>

<!-- Footer -->
<footer id="footer" class="footer">
  <div class="footer_separator"></div>
  <div class="main_footer container-fluid">
    <div class="container">
      <ul class="footer_list footer_info">
        <li><span><i class="fa fa-copyright"></i>GForum since 2017</span></li>
        <li><a href="#">Contact</a></li>
        <li><a href="#">Legal Information</a></li>
        <li><a href="#">Cookies Policy</a></i></li>
        <li><a href="#">Site Rules</a></li>
      </ul>

      <ul class="footer_list social_media">
        <li><span>Social Media</span></li>
        <li><a href="#"><i class="fa fa-facebook"></i> Facebook</a></li>
        <li><a href="#"><i class="fa fa-twitter"></i> Twitter</a></li>
        <li><a href="#"><i class="fa fa-youtube"></i> Youtube</a></li>
      </ul>
    </div>
  </div>
</footer>

</html>

templates/snippets/bootstrap.html
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
      integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
      crossorigin="anonymous">

templates/snippets/comment_options.html
<!--- If the user is the author show edit and delete --->
{% if comment.author == request.user %}
<b><a href="{% url 'comment:update' pk=comment.pk %}" class="edit_and_delete options">Edit</a></b>
<b><a href="{% url 'comment:delete' pk=comment.pk %}" class="edit_and_delete options">Delete</a></b>
{% endif %}

<!--- If the user is not the author and is authenticated show like and reply options --->
{% if user.is_authenticated and comment.author != request.user %}
<!--- Like option --->
<!--- If you already liked the comment show one icon else show another --->
{% if request.user in comment.score.all %}
<span class="comment_likes_done options"><a href="{% url 'comment:like' pk=comment.pk %}">
  <i class="fa fa-thumbs-up"></i></a>
</span>
{% else %}
<span class="comment_likes options"><a href="{% url 'comment:like' pk=comment.pk %}">
  <i class="fa fa-thumbs-o-up"></i></a>
</span>
{% endif %}

<!--- Report Option --->
<b><a href="{% url 'reports:comment' pk=comment.pk %}" class="edit_and_delete report_link options">
  Report</a></b>

<!--- Reply Option and form --->
<b><a href="javascript:" class="edit_and_delete reply_link options">Reply</a></b>
<form class="reply_form" method="post" action="{% url 'comment:reply' slug=object.slug pk=comment.pk %}">
  {% csrf_token %}
  <span class="comment_form">{{ form.as_p }}</span>
  <button type="submit" class="btn btn-default save_button">Save</button>
  <button type="button" class="btn btn-secondary cancel_button cancel_reply">Cancel</button>
</form>
{% endif %}

<!--- If there are likes show the count --->
{% if comment.score.count > 0 %}
<span class="num_likes">
  {{ comment.score.count }}
  <span class="fa-stack fa-lg">
    <i class="fa fa-circle fa-stack-2x"></i>
    <i class="fa fa-thumbs-o-up fa-stack-1x fa-inverse"></i>
  </span>
</span>
{% endif %}

<!--- If there are replies show the option to display them --->
{% if comment.replies.all %}
  <a href="javascript:" class=replies_link>{{comment.replies.all|length}}
    {% if comment.replies.all|length > 1 %}Replies{% else %}Reply{% endif %}
    <i class="fa fa-caret-down"></i>
  </a>
{% endif %}

<!--- Replies Container --->
<div class="show_replies">
  {% for reply in comment.replies.all %}
  <!--- Reply --->
  <div class="reply_container">
    <span class="comment_identifier">#{{ reply.identifier }} </span>
    <b class="comment_author">{{ reply.author }}</b>
    <span class="comment_info"> {{ reply.created|timesince }} ago</span>
    <p>{{ reply.content | safe }}</p>
  </div>
  {% endfor %}
</div>

templates/snippets/delete_confirmation.html
{% extends "snippets/base.html" %}
{% block content %}
<div class="container" id="delete_confirmation_container">
  <form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to <b>delete</b> it?</p>
    <button type="submit" class="btn btn-danger">Confirm</button>
    <a href="{{ object.get_absolute_url }}"><button type="button" class="btn btn-secondary">Cancel</button></a>
  </form>
</div>
{% endblock %}

templates/snippets/display_messages.html
{% if messages %}
{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <center>
    {{message}}
  </center>
</div>
{% endfor %}
{% endif %}

templates/snippets/form.html
{% extends "snippets/base.html" %}{% block title %}{{ title }}{% endblock %}
{% block content %}

<div class="container" id="form_container">

  <form method="POST">{% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Save</button>
  </form>
</div>

{% endblock %}

templates/snippets/forum_categories.html
<!-- Forum Category -->
<div class="col-lg-5 col-sm-9 col-12 categories">
  <div class="row">
    <!-- Icon -->
    <div class="col-lg-2 col-3 icon_col category_col">
      <img src="{{ forum.icon.url }}" />
    </div>

    <!-- Info -->
    <div class="col-lg-10 col-9 info_col category_col">
      <h4>{{ forum.name }}</h4>
      <p>
        {{ forum.description }}
      </p>
    </div>
    
  </div>
</div>

templates/snippets/general_style.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}"/>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
{% include "snippets/tinymce_key.html" %}
<script type="text/javascript" src="{% static 'js/tinymce.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Arimo|Lobster" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto+Slab" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Condensed" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
<link rel="shortcut icon" type="image/png" href="{% static 'images/world-logo.png' %}"/>

templates/snippets/javascript.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

templates/snippets/message-replies.html
<div class="thread_message">
  <h3 class="message_title">{{ reply.subject }}</h3>
  <span class="message_info">from <b class="author">{{ reply.author }}</b> to <b class="contact">{{ reply.contact }}</b> {{ reply.created|timesince }} ago</span>
  <p class="message_content">
    {{ reply.content |safe }}
  </p>
</div>

templates/snippets/nav.html
<nav class="navbar navbar-expand-lg navbar-custom fixed-top">
    <!-- Brand and toggle -->
    <a class="navbar-brand" href="{% url 'index' %}">
      {% load static %}<img src="{% static 'images/world-logo.png' %}" alt="Logo"/>GForum</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_navbar" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="fa fa-bars"></span>
    </button>

    <!-- Wrapper -->
    <div class="collapse navbar-collapse" id="main_navbar"><!-- Target of the toggler -->

      <!-- Left searchbar -->
      <div id="nav_searchbar">
        <form class="form-inline" method="get" action="{% url 'post:search' %}">
          <input class="form-control" type="text" name="q" placeholder="What are you looking for?"
          aria-label="Search" value="{{ request.GET.q }}">
          <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </form>
      </div>


        <!-- Right elements -->
        <ul class="navbar-nav ml-auto">
          <!-- If the user is authenticated show user options -->
            {% if user.is_authenticated %}
            <!-- User -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="nav_username">
                  <!-- If the user has image use it, else use the default image -->
                  {% if user.userprofile.image %}
                  <img class="rounded-circle navbar-pic" src="{{ user.userprofile.image.url }}">
                  {% else %}

                  {% load static %}
                  <img class="rounded-circle navbar-pic" src="{% static 'images/default-profile.png' %}">
                  {% endif %}

                  <span id="user_name">{{user.username}}</span>
                  <span class="sr-only">(current)</span>
                </a>
                <!-- Dropdown Options -->
                <div class="dropdown-menu" id="user_dropdown">
                  <a class="dropdown-item" href="{% url 'accounts:profile' user=request.user.username %}">Profile</a>
                  <a class="dropdown-item" href="{% url 'accounts:settings' user=request.user.username %}">Settings</a>
                  <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
            </li>

            <!-- Notifications -->
            <li class="nav-item" id="notification_wrapper">
                <i id="notifications_icon" class="fa fa-exclamation-circle fa-2x nav-link"></i>
                <!-- If there are active notifications show the alert -->
                {% if active_notifications %}
                <div id="notification_alert">
                  <span id="notification_alert_text">{{active_notifications|length}}</span>
                </div>
                {% endif %}
                <!-- Notifications Popup -->
                {% include "snippets/notifications_popup.html" %}
            </li>

            <!-- Messages -->
            <li id="messages_wrapper" class="nav-item">
                <a href="{% url 'messages:inbox' %}"><i class="fa fa-envelope-o fa-2x nav-link"></i></a>
                <!-- If there are active messages show the alert -->
                {% if active_messages %}
                <div id="messages_alert">
                  <span id="messages_alert_text">{{active_messages|length}}</span>
                </div>
                {% endif %}
            </li>

            <!-- If the user is not authenticated show login and register options -->
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:login' %}">
                  <i class="fa fa-sign-in fa-2x"></i></a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:register' %}">
                  <i class="fa fa-user-plus fa-2x"></i></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/snippets/notifications_popup.html
<i id="notification_caret" class="fa fa-caret-up notifications_popup"></i>

<div id="notifications_container" class="notifications_popup"> <!-- Wrapper -->
  <span>Notifications</span>

  <div id="notifications_container_list"> <!-- List of notifications -->

    {% for notification in user.user_notifications.all %}
    <!-- If the notification is active apply an extra class/style -->
    {% if notification.active %}
    <div class="notification notification_active">
    {% else %}
    <div class="notification">
    {% endif %}

      <!-- Notification -->
      <div class="row">
        <!-- Notification Image -->
        <div class="notification_image col-3">
          {% if notification.author.userprofile.image %}
          <img class="rounded-circle" src="{{notification.author.userprofile.image.url}}"/>
          {% else %}
          {% load static %}
          <img class="rounded-circle" src="{% static 'images/default-profile.png' %}">
          {% endif %}
        </div>

        <!-- Notification Info -->
        <div class="notification_info col-9">
          <a href="{% url 'notification:details' pk=notification.pk %}">
            {{notification.content}}
          </a>
          <!-- Show different icons for like/comment events -->
          <br />{% if notification.is_like %}
          <i class="fa fa-thumbs-up"></i>
          {% else %}
          <i class="fa fa-comment"></i>
          {% endif %}
          <!-- Time ago since the notification was created -->
          <span>{{notification.creation|timesince}} ago</span>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>