apps/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from .views import (login_view, logout_view, register_view, UserProfileView,
                    UpdateProfile, activate)


urlpatterns = [
    url(r'^login/$', login_view, name="login"),
    url(r'^logout/$', logout_view, name="logout"),
    url(r'^register/$', register_view, name="register"),
    url(r'^profile/(?P<user>[\w-]+)/$', UserProfileView.as_view(), name="profile"),
    url(r'^profile/settings/(?P<user>[\w-]+)/$', UpdateProfile.as_view(), name="settings"),

    # password activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name="activate"),

    # password reset urls
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),

    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),



]

apps/private_messages/urls.py
from django.conf.urls import url
from .views import PMList, CreatePM, SentList, ReplyPM, DeletePM, ProfilePM

urlpatterns = [
    url(r'^inbox/$', PMList.as_view(), name="inbox"),
    url(r'^sent/$', SentList.as_view(), name="sent"),
    url(r'^create/$', CreatePM.as_view(), name="create"),
    url(r'^reply/(?P<contact>[\w-]+)/(?P<pk>\d+)/$', ReplyPM.as_view(), name="reply"),
    url(r'^delete/(?P<pk>\d+)/$', DeletePM.as_view(), name="delete"),
    url(r'^create/(?P<contact>[\w-]+)/$', ProfilePM.as_view(), name="profile_message"),
]

config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from apps.forum.views import ForumList

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', ForumList.as_view(), name="index"),
    url(r'^forum/', include("apps.forum.urls", namespace="forum")),
    url(r'^post/', include("apps.posts.urls", namespace="post")),
    url(r'^comment/', include("apps.comments.urls", namespace="comment")),
    url(r'^accounts/', include("apps.accounts.urls", namespace="accounts")),
    url(r'^messages/', include("apps.private_messages.urls", namespace="messages")),
    url(r'^reports/', include("apps.reports.urls", namespace="reports")),
    url(r'^notification/', include("apps.notifications.urls", namespace="notification")),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/private_messages/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse

User = settings.AUTH_USER_MODEL


class PrivateMessage(models.Model):
    author = models.ForeignKey(User, related_name="sender")
    contact = models.ForeignKey(User, related_name="receiver")
    subject = models.CharField(max_length=120)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey("self", null=True, blank=True, related_name="replies")
    is_reply = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    def __str__(self):
        basic_description = str(self.author) + " to " + str(self.contact) + " | " + str(self.subject)
        return basic_description

    def get_absolute_url(self):
        return reverse("messages:sent")

apps/private_messages/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import PrivateMessage

User = get_user_model()


class PMCreateForm(forms.ModelForm):
    contact_username = forms.CharField(label="", max_length=120, widget=forms.TextInput(attrs={"placeholder": "to... (username)"}))
    subject = forms.CharField(label="", max_length=120, widget=forms.TextInput(attrs={"placeholder": "Subject"}))
    content = forms.CharField(label="", max_length=10000, widget=forms.Textarea(
    attrs={"class": "form-control message-form", "placeholder": "Write your message here.."}))

    class Meta:
        model = PrivateMessage
        fields = [
        "contact_username",
        "subject",
        "content"
        ]

    # id the contact username does not exist raise a validation error
    def clean(self, *args, **kwargs):
        contact = self.cleaned_data.get("contact_username")
        try:
            contact = User.objects.get(username=contact)
        except User.DoesNotExist:
            raise forms.ValidationError("This username does not exist.")

        return super(PMCreateForm, self).clean(*args, **kwargs)


class PMReplyForm(forms.ModelForm):
    subject = forms.CharField(label="", max_length=120, widget=forms.TextInput(attrs={"placeholder": "Subject"}))
    content = forms.CharField(label="", widget=forms.Textarea(
    attrs={"class": "form-control message-form", "placeholder": "Write your message here.."}))

    class Meta:
        model = PrivateMessage
        fields = [
        "subject",
        "content"
        ]

apps/private_messages/views.py
from django.shortcuts import reverse
from django.views.generic import ListView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib import messages

from .models import PrivateMessage
from .forms import PMCreateForm, PMReplyForm

User = get_user_model()


# returns all the received private messages for the user
class PMList(LoginRequiredMixin, ListView):

    def get_queryset(self):
        pms = PrivateMessage.objects.filter(contact=self.request.user)
        pms.update(active=False)
        return pms

    def get_context_data(self, *args, **kwargs):
        context = super(PMList, self).get_context_data(*args, **kwargs)
        context["title"] = "Inbox"
        context["form"] = PMReplyForm
        return context


# returns all the sent private messages for the user
class SentList(LoginRequiredMixin, ListView):
    def get_queryset(self):
        return PrivateMessage.objects.filter(author=self.request.user)

    def get_context_data(self, *args, **kwargs):
        context = super(SentList, self).get_context_data(*args, **kwargs)
        context["title"] = "Sent Messages"
        context["sent"] = True
        storage = messages.get_messages(self.request)  # gets all the django messages to be displayed
        context["messages"] = storage
        return context


# creates a new private message
class CreatePM(LoginRequiredMixin, CreateView):
    form_class = PMCreateForm
    template_name = "snippets/form.html"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        contact_username = form.cleaned_data.get("contact_username")
        instance.contact = User.objects.get(username__iexact=contact_username)
        messages.success(self.request, "Your message has been sent.")  # creates a django message
        return super(CreatePM, self).form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super(CreatePM, self).get_context_data(*args, **kwargs)
        context["title"] = "New Message"
        return context


# creates a new private message for the owner of the profile
class ProfilePM(LoginRequiredMixin, CreateView):
    form_class = PMReplyForm
    template_name = "snippets/form.html"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        contact_username = self.kwargs.get("contact")
        instance.contact = User.objects.get(username__iexact=contact_username)
        messages.success(self.request, "Your message has been sent.")  # creates a django message
        return super(ProfilePM, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(ProfilePM, self).get_context_data(**kwargs)
        context["title"] = "New message to " + self.kwargs.get("contact")
        return context


# delete a received private message
class DeletePM(LoginRequiredMixin, DeleteView):
    model = PrivateMessage
    template_name = "snippets/delete_confirmation.html"

    def get_queryset(self):
        return PrivateMessage.objects.filter(contact=self.request.user)

    def get_success_url(self):
        return reverse("messages:inbox")


# reply to a received message
class ReplyPM(LoginRequiredMixin, CreateView):
    form_class = PMReplyForm
    template_name = "snippets/form.html"

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.author = self.request.user
        contact_username = self.kwargs.get("contact")
        instance.contact = User.objects.get(username__iexact=contact_username)
        instance.is_reply = True
        parent_pk = self.kwargs.get("pk")
        parent = PrivateMessage.objects.get(pk=parent_pk)  # gets the message to which we are responding
        # if the message is also a reply set the parent to the message parent (parent of the parent)
        # this will allow all the replies to have the same parent (the message that initiated the thread)
        if parent.is_reply:
            parent = parent.parent
        instance.parent = parent
        messages.success(self.request, "Your reply has been sent.")
        return super(ReplyPM, self).form_valid(form)

templates/private_messages/privatemessage_list.html
{% extends "snippets/base.html" %} {% block title %}{{ title }}{% endblock %} {% block content %}

<div id="messages_container" class="container">

  <!-- New message button -->
  <a href="{% url 'messages:create' %}"><button class="btn btn-default" type="button" id="create_message">
    <i class="fa fa-pencil"></i></button></a>
  <!-- Inbox/Sent filters -->
  <div id="message_labels_container">
    <a href="{% url 'messages:inbox' %}" class="btn btn-default label active">Inbox</a>
    <a href="{% url 'messages:sent' %}" class="btn btn-default label">Sent</a>
  </div>

  <!-- Private Messages List -->
  <div id="pm_list">
    {% for object in object_list reversed %}
    <!-- Private Message -->
    <div class="message_container">
      <!-- Title -->
      <h3 class="message_title">{{ object.subject }}</h3>
      <!-- If inbox show author, if sent show contact -->
      {% if sent %}
      <span class="message_info">
        to <a href="{% url 'accounts:profile' user=object.contact.username %}">
        <b class="contact">{{ object.contact }}</b></a>
      </span>
      {% else %}
      <span class="message_info">
        from <a href="{% url 'accounts:profile' user=object.author.username %}">
        <b class="author">{{ object.author }}</b></a>
      </span>
      {% endif %}
      <!-- Time since -->
      <span class="time_info">{{ object.created|timesince }} ago</span>

      <!-- Content -->
      <p class="message_content">{{ object.content | safe }}</p>

      <!-- If the object or the parent have replies (a thread) show option -->
      {% if object.replies.all or object.parent.replies.all %}
      <a href="javascript:" class="replies_link messages_thread">Show Thread<i class="fa fa-caret-down"></i></a>

      <!-- Replies -->
      <div class="show_replies">
        <!-- If the object don't have a parent (it is the parent) show all the replies -->
        {% if not object.parent %}

        {% for reply in object.replies.all %}
        {% include 'snippets/message-replies.html' %}
        {% endfor %}

        <!-- If the object has a parent show the parent and then the replies -->
        {% else %}
        <!-- Parent -->
        <div class="thread_message">
          <h3 class="message_title">{{ object.parent.subject }}</h3>
          <span class="message_info">from <b class="author">{{ object.parent.author }}</b>
             to <b class="contact">{{ object.parent.contact }}</b>
             {{ object.parent.created|timesince }} ago</span>
          <p class="message_content">
            {{ object.parent.content }}
          </p>
        </div>
        <!-- Replies -->
        {% for reply in object.parent.replies.all %}
        {% include 'snippets/message-replies.html' %}
        {% endfor %}

        {% endif %}
      </div>
      {% endif %}

      <!-- If inbox show options -->
      {% if not sent %}
      <b><a href="{% url 'messages:delete' pk=object.pk %}" class="edit_and_delete options">Delete</a></b>
      <b><a href="javascript:" class="edit_and_delete reply_pm options">Reply</a></b>

      <form class="reply_form" action="{% url 'messages:reply' contact=object.author.username pk=object.pk %}" method="post">
        {% csrf_token %} {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
        <button type="button" class="btn btn-secondary cancel_reply">Cancel</button>
      </form>
      {% endif %}

    </div>
    {% endfor %}
  </div>
</div>

{%block head %}
<!-- Selected filter activation -->
<script>
  var loc = window.location.pathname;
  $('#message_labels_container').find('.label').each(function() {
    $(this).toggleClass('active', $(this).attr('href') == loc);
  });
</script>
{% endblock %}
{% endblock %}